package pgcatalog

import (
	"petacore/internal/runtime/rhelpers"
	"petacore/internal/runtime/rsql/statements"
)

func ExecutePgProc(stmt *statements.SelectStatement) ([]map[string]interface{}, error) {
	allRows := []map[string]interface{}{
		{
			"oid":             31,
			"proname":         "boolin",
			"pronamespace":    11,
			"proowner":        10,
			"prolang":         12,
			"procost":         1,
			"prorows":         0,
			"provariadic":     0,
			"protransform":    "-",
			"proisagg":        false,
			"proiswindow":     false,
			"prosecdef":       false,
			"proleakproof":    true,
			"proisstrict":     true,
			"proretset":       false,
			"provolatile":     "i",
			"proparallel":     "s",
			"pronargs":        1,
			"pronargdefaults": 0,
			"prorettype":      16,
			"proargtypes":     []int{25},
			"proallargtypes":  nil,
			"proargmodes":     nil,
			"proargnames":     []string{"arg"},
			"proargdefaults":  nil,
			"protrftypes":     nil,
			"prosrc":          "boolin",
			"probin":          "-",
			"proconfig":       nil,
			"proacl":          nil,
		},
		{
			"oid":             32,
			"proname":         "boolout",
			"pronamespace":    11,
			"proowner":        10,
			"prolang":         12,
			"procost":         1,
			"prorows":         0,
			"provariadic":     0,
			"protransform":    "-",
			"proisagg":        false,
			"proiswindow":     false,
			"prosecdef":       false,
			"proleakproof":    true,
			"proisstrict":     true,
			"proretset":       false,
			"provolatile":     "i",
			"proparallel":     "s",
			"pronargs":        1,
			"pronargdefaults": 0,
			"prorettype":      25,
			"proargtypes":     []int{16},
			"proallargtypes":  nil,
			"proargmodes":     nil,
			"proargnames":     []string{"arg"},
			"proargdefaults":  nil,
			"protrftypes":     nil,
			"prosrc":          "boolout",
			"probin":          "-",
			"proconfig":       nil,
			"proacl":          nil,
		},
		{
			"oid":             33,
			"proname":         "byteain",
			"pronamespace":    11,
			"proowner":        10,
			"prolang":         12,
			"procost":         1,
			"prorows":         0,
			"provariadic":     0,
			"protransform":    "-",
			"proisagg":        false,
			"proiswindow":     false,
			"prosecdef":       false,
			"proleakproof":    true,
			"proisstrict":     true,
			"proretset":       false,
			"provolatile":     "i",
			"proparallel":     "s",
			"pronargs":        1,
			"pronargdefaults": 0,
			"prorettype":      17,
			"proargtypes":     []int{25},
			"proallargtypes":  nil,
			"proargmodes":     nil,
			"proargnames":     []string{"arg"},
			"proargdefaults":  nil,
			"protrftypes":     nil,
			"prosrc":          "byteain",
			"probin":          "-",
			"proconfig":       nil,
			"proacl":          nil,
		},
		{
			"oid":             34,
			"proname":         "byteaout",
			"pronamespace":    11,
			"proowner":        10,
			"prolang":         12,
			"procost":         1,
			"prorows":         0,
			"provariadic":     0,
			"protransform":    "-",
			"proisagg":        false,
			"proiswindow":     false,
			"prosecdef":       false,
			"proleakproof":    true,
			"proisstrict":     true,
			"proretset":       false,
			"provolatile":     "i",
			"proparallel":     "s",
			"pronargs":        1,
			"pronargdefaults": 0,
			"prorettype":      25,
			"proargtypes":     []int{17},
			"proallargtypes":  nil,
			"proargmodes":     nil,
			"proargnames":     []string{"arg"},
			"proargdefaults":  nil,
			"protrftypes":     nil,
			"prosrc":          "byteaout",
			"probin":          "-",
			"proconfig":       nil,
			"proacl":          nil,
		},
		{
			"oid":             38,
			"proname":         "int4in",
			"pronamespace":    11,
			"proowner":        10,
			"prolang":         12,
			"procost":         1,
			"prorows":         0,
			"provariadic":     0,
			"protransform":    "-",
			"proisagg":        false,
			"proiswindow":     false,
			"prosecdef":       false,
			"proleakproof":    true,
			"proisstrict":     true,
			"proretset":       false,
			"provolatile":     "i",
			"proparallel":     "s",
			"pronargs":        1,
			"pronargdefaults": 0,
			"prorettype":      23,
			"proargtypes":     []int{25},
			"proallargtypes":  nil,
			"proargmodes":     nil,
			"proargnames":     []string{"arg"},
			"proargdefaults":  nil,
			"protrftypes":     nil,
			"prosrc":          "int4in",
			"probin":          "-",
			"proconfig":       nil,
			"proacl":          nil,
		},
		{
			"oid":             39,
			"proname":         "int4out",
			"pronamespace":    11,
			"proowner":        10,
			"prolang":         12,
			"procost":         1,
			"prorows":         0,
			"provariadic":     0,
			"protransform":    "-",
			"proisagg":        false,
			"proiswindow":     false,
			"prosecdef":       false,
			"proleakproof":    true,
			"proisstrict":     true,
			"proretset":       false,
			"provolatile":     "i",
			"proparallel":     "s",
			"pronargs":        1,
			"pronargdefaults": 0,
			"prorettype":      25,
			"proargtypes":     []int{23},
			"proallargtypes":  nil,
			"proargmodes":     nil,
			"proargnames":     []string{"arg"},
			"proargdefaults":  nil,
			"protrftypes":     nil,
			"prosrc":          "int4out",
			"probin":          "-",
			"proconfig":       nil,
			"proacl":          nil,
		},
		{
			"oid":             44,
			"proname":         "textin",
			"pronamespace":    11,
			"proowner":        10,
			"prolang":         12,
			"procost":         1,
			"prorows":         0,
			"provariadic":     0,
			"protransform":    "-",
			"proisagg":        false,
			"proiswindow":     false,
			"prosecdef":       false,
			"proleakproof":    true,
			"proisstrict":     true,
			"proretset":       false,
			"provolatile":     "i",
			"proparallel":     "s",
			"pronargs":        1,
			"pronargdefaults": 0,
			"prorettype":      25,
			"proargtypes":     []int{25},
			"proallargtypes":  nil,
			"proargmodes":     nil,
			"proargnames":     []string{"arg"},
			"proargdefaults":  nil,
			"protrftypes":     nil,
			"prosrc":          "textin",
			"probin":          "-",
			"proconfig":       nil,
			"proacl":          nil,
		},
		{
			"oid":             45,
			"proname":         "textout",
			"pronamespace":    11,
			"proowner":        10,
			"prolang":         12,
			"procost":         1,
			"prorows":         0,
			"provariadic":     0,
			"protransform":    "-",
			"proisagg":        false,
			"proiswindow":     false,
			"prosecdef":       false,
			"proleakproof":    true,
			"proisstrict":     true,
			"proretset":       false,
			"provolatile":     "i",
			"proparallel":     "s",
			"pronargs":        1,
			"pronargdefaults": 0,
			"prorettype":      25,
			"proargtypes":     []int{25},
			"proallargtypes":  nil,
			"proargmodes":     nil,
			"proargnames":     []string{"arg"},
			"proargdefaults":  nil,
			"protrftypes":     nil,
			"prosrc":          "textout",
			"probin":          "-",
			"proconfig":       nil,
			"proacl":          nil,
		},
	}
	return rhelpers.FilterColumns(allRows, stmt), nil
}
