package pgcatalog

import (
	"petacore/internal/runtime/rhelpers"
	"petacore/internal/runtime/rsql/statements"
)

func ExecutePgTypeExpanded(stmt *statements.SelectStatement) ([]map[string]interface{}, error) {
	allRows := []map[string]interface{}{
		{
			"oid":            16,
			"typname":        "bool",
			"typnamespace":   11,
			"typowner":       10,
			"typlen":         1,
			"typbyval":       true,
			"typtype":        "b",
			"typcategory":    "B",
			"typispreferred": true,
			"typisdefined":   true,
			"typdelim":       ",",
			"typrelid":       0,
			"typelem":        0,
			"typarray":       1000,
			"typinput":       "boolin",
			"typoutput":      "boolout",
			"typreceive":     "boolrecv",
			"typsend":        "boolsend",
			"typmodin":       "-",
			"typmodout":      "-",
			"typanalyze":     "-",
			"typalign":       "c",
			"typstorage":     "p",
			"typnotnull":     false,
			"typbasetype":    0,
			"typtypmod":      -1,
			"typndims":       0,
			"typcollation":   0,
			"typdefaultbin":  nil,
			"typdefault":     nil,
			"typacl":         nil,
		},
		{
			"oid":            19,
			"typname":        "name",
			"typnamespace":   11,
			"typowner":       10,
			"typlen":         64,
			"typbyval":       false,
			"typtype":        "b",
			"typcategory":    "S",
			"typispreferred": false,
			"typisdefined":   true,
			"typdelim":       ",",
			"typrelid":       0,
			"typelem":        0,
			"typarray":       0,
			"typinput":       "namein",
			"typoutput":      "nameout",
			"typreceive":     "namerecv",
			"typsend":        "namesend",
			"typmodin":       "-",
			"typmodout":      "-",
			"typanalyze":     "-",
			"typalign":       "c",
			"typstorage":     "p",
			"typnotnull":     false,
			"typbasetype":    0,
			"typtypmod":      -1,
			"typndims":       0,
			"typcollation":   0,
			"typdefaultbin":  nil,
			"typdefault":     nil,
			"typacl":         nil,
		},
		{
			"oid":            23,
			"typname":        "int4",
			"typnamespace":   11,
			"typowner":       10,
			"typlen":         4,
			"typbyval":       true,
			"typtype":        "b",
			"typcategory":    "N",
			"typispreferred": false,
			"typisdefined":   true,
			"typdelim":       ",",
			"typrelid":       0,
			"typelem":        0,
			"typarray":       1007,
			"typinput":       "int4in",
			"typoutput":      "int4out",
			"typreceive":     "int4recv",
			"typsend":        "int4send",
			"typmodin":       "-",
			"typmodout":      "-",
			"typanalyze":     "-",
			"typalign":       "i",
			"typstorage":     "p",
			"typnotnull":     false,
			"typbasetype":    0,
			"typtypmod":      -1,
			"typndims":       0,
			"typcollation":   0,
			"typdefaultbin":  nil,
			"typdefault":     nil,
			"typacl":         nil,
		},
		{
			"oid":            25,
			"typname":        "text",
			"typnamespace":   11,
			"typowner":       10,
			"typlen":         -1,
			"typbyval":       false,
			"typtype":        "b",
			"typcategory":    "S",
			"typispreferred": true,
			"typisdefined":   true,
			"typdelim":       ",",
			"typrelid":       0,
			"typelem":        0,
			"typarray":       1009,
			"typinput":       "textin",
			"typoutput":      "textout",
			"typreceive":     "textrecv",
			"typsend":        "textsend",
			"typmodin":       "-",
			"typmodout":      "-",
			"typanalyze":     "-",
			"typalign":       "i",
			"typstorage":     "x",
			"typnotnull":     false,
			"typbasetype":    0,
			"typtypmod":      -1,
			"typndims":       0,
			"typcollation":   100,
			"typdefaultbin":  nil,
			"typdefault":     nil,
			"typacl":         nil,
		},
		{
			"oid":            26,
			"typname":        "oid",
			"typnamespace":   11,
			"typowner":       10,
			"typlen":         4,
			"typbyval":       true,
			"typtype":        "b",
			"typcategory":    "N",
			"typispreferred": false,
			"typisdefined":   true,
			"typdelim":       ",",
			"typrelid":       0,
			"typelem":        0,
			"typarray":       1028,
			"typinput":       "oidin",
			"typoutput":      "oidout",
			"typreceive":     "oidrecv",
			"typsend":        "oidsand",
			"typmodin":       "-",
			"typmodout":      "-",
			"typanalyze":     "-",
			"typalign":       "i",
			"typstorage":     "p",
			"typnotnull":     false,
			"typbasetype":    0,
			"typtypmod":      -1,
			"typndims":       0,
			"typcollation":   0,
			"typdefaultbin":  nil,
			"typdefault":     nil,
			"typacl":         nil,
		},
	}
	return rhelpers.FilterColumns(allRows, stmt), nil
}
